# Generated by Django 5.1.2 on 2024-10-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QA_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcq",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
    ]
